{
    "type": "bundle",
    "id": "bundle--aeb54348-aebe-4006-881e-5db24e3227ab",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--77ea06c0-0c62-49df-983e-8629ca6135f6",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:29.446845Z",
            "modified": "2021-03-13T20:12:29.446845Z",
            "name": "CVE-2020-9111",
            "description": "E6878-370 versions 10.0.3.1(H557SP27C233),10.0.3.1(H563SP21C233) and E6878-870 versions 10.0.3.1(H557SP27C233),10.0.3.1(H563SP11C233) have a denial of service vulnerability. The system does not properly check some events, an attacker could launch the events continually, successful exploit could cause reboot of the process.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-9111"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}