{
    "type": "bundle",
    "id": "bundle--9d9ccd0c-3fbc-4f8b-8d49-1f728f79d4c3",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--90c763f0-c286-4f60-84d5-9c8901dde8f4",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:15.617145Z",
            "modified": "2021-03-13T20:11:15.617145Z",
            "name": "CVE-2017-9186",
            "description": "libautotrace.a in AutoTrace 0.31.1 has a \"cannot be represented in type int\" issue in input-bmp.c:326:17.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2017-9186"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}