{
    "type": "bundle",
    "id": "bundle--0f6ca257-a608-4941-8ca4-eece11970b7a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--142035a5-af1a-411d-bfda-91733cbdf460",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:16.168429Z",
            "modified": "2021-03-13T20:11:16.168429Z",
            "name": "CVE-2017-9183",
            "description": "libautotrace.a in AutoTrace 0.31.1 has a \"cannot be represented in type int\" issue in input-bmp.c:309:7.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2017-9183"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}