{
    "type": "bundle",
    "id": "bundle--c4e26a6e-0c74-400b-8f55-9c8e933f7ae5",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--4ee21cc4-0017-4cbe-a55d-bbfe45ac4dbb",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:23.029714Z",
            "modified": "2021-03-13T20:11:23.029714Z",
            "name": "CVE-2017-16637",
            "description": "In Vectura Perfect Privacy VPN Manager v1.10.10 and v1.10.11, when resetting the network data via the software client, with a running VPN connection, a critical error occurs which leads to a \"FrmAdvancedProtection\" crash. Although the mechanism malfunctions and an error occurs during the runtime with the stack trace being issued, the software process is not properly terminated. The software client is still attempting to maintain the connection even though the network connection information is being reset live. In that insecure mode, the \"FrmAdvancedProtection\" component crashes, but the process continues to run with different errors and process corruptions. This local corruption vulnerability can be exploited by local attackers.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2017-16637"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}