{
    "type": "bundle",
    "id": "bundle--95d2cf0f-8e3f-413e-81fe-289c3d8b9bcd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--eff9adf9-14e2-41e9-bc05-2abbd0100c41",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:49.149848Z",
            "modified": "2021-03-13T20:11:49.149848Z",
            "name": "CVE-2019-15917",
            "description": "An issue was discovered in the Linux kernel before 5.0.5. There is a use-after-free issue when hci_uart_register_dev() fails in hci_uart_set_proto() in drivers/bluetooth/hci_ldisc.c.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-15917"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}