{
    "type": "bundle",
    "id": "bundle--5b346162-8c78-4e24-9d1d-52e063134d18",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--de9f23f7-4c81-4e5b-81b0-7237b416041c",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:29.785934Z",
            "modified": "2021-03-13T20:12:29.785934Z",
            "name": "CVE-2020-9847",
            "description": "An out-of-bounds read was addressed with improved bounds checking. This issue is fixed in macOS Catalina 10.15.5. A malicious application may be able to break out of its sandbox.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-9847"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}