{
    "type": "bundle",
    "id": "bundle--5a1338ac-8b5e-4143-9ba7-f5910768daf5",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--a34b3efe-128c-496e-898f-d705c2ae0dd0",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:13:01.782256Z",
            "modified": "2021-03-13T20:13:01.782256Z",
            "name": "CVE-2018-10883",
            "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bounds write in jbd2_journal_dirty_metadata(), a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-10883"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}