{
    "type": "bundle",
    "id": "bundle--a719278b-171f-4005-9075-af1be1068eb5",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--64f564ce-3ccb-4e7c-90ea-9dde16cf67eb",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:13:08.859755Z",
            "modified": "2021-03-13T20:13:08.859755Z",
            "name": "CVE-2018-4365",
            "description": "An out-of-bounds read was addressed with improved bounds checking. This issue affected versions prior to iOS 12.1.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-4365"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}