{
    "type": "bundle",
    "id": "bundle--8bc04a7f-1497-4e87-8d06-9f3c1993de52",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--6a352139-a387-4dd9-94e5-49ddea71d502",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:09:24.361227Z",
            "modified": "2021-03-13T20:09:24.361227Z",
            "name": "CVE-2013-7338",
            "description": "Python before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2013-7338"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}